# Generated by Django 3.2 on 2021-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='站点编号')),
                ('station_name', models.CharField(max_length=255, verbose_name='站点名称')),
                ('station_route', models.CharField(max_length=255, verbose_name='行驶路线')),
                ('admin_area', models.CharField(max_length=255, verbose_name='行政区域')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete', 'exports'),
            },
        ),
    ]
